---
- name: Start named service
  service:
    name: named 
    state: start 
    enabled: yes 

- name: Add port to firewall
  firewalld:
    service: dns
    permanent: yes 
    state: enabled 
    zone: public
