---
- hosts: all
  vars_files:
    - ../vars/named_vars.yaml
  
  tasks:
  - name: Prerequisites
    import_tasks: prerequisites.yaml
  
  - name: Config named.service
    import_tasks: config_named.yaml
